version: '3.9'

networks:
  vulnshop-network:
    driver: bridge

services: 
  postgresql:
    image: postgres:12.4
    container_name: vuln-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vulnshop
    ports:
      - 5432:5432
    networks: 
      - vulnshop-network
